server:
  port: 8081
spring:
  profiles:
    active: local # 기본 환경 선택

---
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      username: manager
      password: duddus186213!
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/woori

  flyway:
    enabled: false

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            client-secret:


